### PR TITLE
Massive rewrite of Lib5K motors and sensors

### PR DESCRIPTION
**Pull request by ewpratten**
Remember issue #3? This PR is the solution... And a lot more.

## Changelog

Here is a list of everything changed:
 - GearBox and GearBoxEncoder are now deprecated
 - Added many new interfaces
   - IMotorCollection
     - A common interface for any collection of motor controllers. Is inter-compatible with WPILib's `SpeedController`
   - ICurrentController
     - A common interface for devices that allow current limiting and voltage compensation
     - Is used to provide a much simpler interface for setting TalonSRX limits, but can probably be used for other controllers too
   - IMotorGroupSafety
     - Provides `setSafetyEnabled` for a group of controllers
     - Will probably be replaced with some MotorSafety-compatible interface, but works fine for now
   - IEncoderProvider
     - A common interface for things with encoders attached
   - PeriodicComponent
     - A common interface for components that must be updated regularly in a loop (usually in RobotPeriodic)
   - Loggable
     - A common interface for components that can be logged to the robot log, and can have their telemetry data pushed to NetworkTables
 - Replaced GearBox with multiple new classes
   - TalonSRXCollection
     - A collection of 2 or more `WPI_TalonSRX` objects. 
     - Acts like a `SpeedControllerGroup`
     - Implements `IMotorCollection`, `ICurrentController`, `IEncoderProvider`, `IMotorGroupSafety`, and `Loggable`
     - Provides it's own `getMaster` method to allow Talon-specific settings to be set
     - All slaves are configured using CTRE's `follow` system. This allows settings to me set once on the master controller, then be automatically copied to the slaves
   - SparkCollection
     - A collection of 2 or more `Spark` objects. 
     - Acts like a `SpeedControllerGroup`
     - Implements `IMotorCollection`, and `Loggable`
   - MixedMotorCollection
     - A collection of 2 or more motor controllers of any type, in any order.
     - Acts like a `SpeedControllerGroup`
     - Implements `IMotorCollection`, and `Loggable`
 - Added another `log` method to RobotLogger that allows the user to specify a component name and mesage, but defaults to `Level.kInfo` for messages
 - Added new base for component telemetry
   - ComponentTelemetry provides a method to produce a NetworkTable, given a component name 
     - Used by the three new MotorCollection classes
     - Should be used with anything that implements `Loggable`
     - Provides a clean NetworkTables tree for telemetry data from Lib5K
 - Added `TalonHelper` to make some TalonSRX configuration easier
 - Documented `EncoderBase` (And moved it to a new package)
 - Replaced `GearBox` with `TalonSRXCollection` in the DriveTrain subsystem
 - Wrote a long changelog :laughing:

## Why?
Great question.

After working on team 6856's snabb last summer with the first version of Lib5K I had many problems when I realized that their bot used [mixed motor controllers](https://github.com/frc5024/Snabb/blob/master/src/main/java/frc/common/wrappers/MixedGearBox.java) (Talons in the front, Victors in the back if I remember correctly). Since then, I have somewhat hated the `GearBox` class I wrote, because it only worked for a collection of exactly 2 TalonSRX controllers, with an encoder attached to the front (MiniBot made me add a switch for encoders later). 

Now, there has been some talk on the team about building a 6-motor drivetrain in 2020. This means that GearBox will need a rewrite. So, to solve all these problems, I just decided to fully replace GearBox with a much more modular system.

## Why use so many interfaces?
Again, making the code modular. If your system only needs to configure motor current limits, you can just use `ICurrentController` objects, and any type of motor, or MotorCollection that provides that interface can be dropped in. It's kinda nice.

## Why re-org the project
Many components got moved around, and placed in sub-packages. This is just to make the project visually cleaner.

### CODE REVIEW

**Comment by ewpratten** [comment]
@ExVacuum @slownie and @hyperliskdev have been requested for reviewing as a sanity check, and because this will probably cause merge conflicts for some of the other branches being worked on

**Comment by ewpratten** [comment]
I just modified the `IEncoderProvider` to allow specification of which encoder to read (in a situation of more than one sensor slot, like multiple Talons, with only one attached to a sensor)

And also added a `getDefaultEncoder()` to get the default (for us lazy people)

**Comment by ewpratten** [comment]
Also, a special thanks to the cup of coffee that got me through writing this this morning :coffee:

**Comment by ewpratten** [comment]
Requested @awpratten to review just for your thoughts

**Comment by ewpratten** [comment]
#28 has fixed some merge conflicts with #27

**Comment by ewpratten** [comment]
## Changes from #30 
 - Added `IVoltageOutputController`
   - Adds `void setVoltage(double volts)` for setting a controller's desired output voltage
   - Adds `double getEstimatedVoltage()` to estimate the output voltage (bus voltage * output percent)
 - `TalonSRXCollection`, `SparkCollection`, and `MixedMotorCollection` all now implement `IVoltageOutputController`

**Comment by ewpratten** [comment]
## Changes from #31 
 - Added `IRampRateController` interface for all controllers with ramp rate control
 -  `TimedSlewLimiter` extends `SlewLimiter` and provides TalonSRX-like ramp control
 -  `TalonSRXCollection`, `SparkCollection`, and `MixedMotorCollection` all now implement `IRampRateController`

**Comment by ewpratten** [comment]
# Description of #32 

Turns out I forgot about the fact we also own [VictorSPX](http://www.ctr-electronics.com/victor-spx.html) motor controllers. So I added support for them. I have not bothered to figure out how to mix talons and victors the "ctre way" yet. Currently, if you want to use both in the same gearbox, use the `MixedMotorController` class. 

CTRE does have a way to let Talons and Victors follow eachother.. Maybe a `CTREControllerCollection` could be made in the future? This would have  to accept `IMotorController` objects instead of a specific controller.

## Changes
 - Added `VictorSPXController`
 - Added `VictorEncoder`

## TODO
As mentioned above, we can still add a `CTREControllerCollection` class. Also, I added `VictorEncoder` but there is no way to easily configure it. Unlike Talons, Victors actually read encoders over the network (cue @hyperliskdev going crazy about network load). Maybe we can add an "easy-config" method for this in the future?

---

This is the last addition for the day. Remember to pull this branch again if you are currently reviewing, as there have been many changes since I started this PR

**Comment by hyperliskdev** [comment]
There is a lot of stuff to go over. This certainly deserves a team wide discussion or at least an hour of describing everything that's going on. Lib5K is going to need a lot of document rewrites also.

As for that TODO, the CTREControllerCollection will encompass both Victor and Talons?

**Comment by hyperliskdev** [comment]
From an understanding perspective, this interface system is great. It makes things way easier to explain without just saying "it do because it do".

**Comment by ewpratten** [comment]
I will be using this to demonstrate the code review process for the new people on tuesday

**Comment by ewpratten** [comment]
And yes, it will encompass both victor and talon. But since `IMotorController` is specifically for CTRE controllers, and not WPILib compatable, we will probably have to create an "adapter" that allows an `IMotorController` to also expose the `SpeedController` interface.

**Comment by ewpratten** [comment]
Just tested this code out on MiniBot. All is functional

**Comment by ewpratten** [comment]
Completely unrelated to motors, I added the rest of the LED driver modes

**Comment by hyperliskdev** [comment]
The LED's were important, thank you for adding this.

**Review by hyperliskdev — APPROVED** [review]
Looks great, super modular and well commented. 
This is going to be a very great during the season.

**Review by rsninja722 — APPROVED** [review]

**Review by wm-c — APPROVED** [review]
dang good code 👍

**Review by Keatonion — APPROVED** [review]

**Comment by SRJacks** [comment]
Good comments, very helpful.

**Review by catarinaburghi — APPROVED** [review]
Great Code!

**Review by SRJacks — APPROVED** [review]
Good.

**Comment by ewpratten** [comment]
@awpratten  has given me permission to override his review, and merge

**Pull request merged**
